### ISSUE TITLE
HTTPS Redirection

### ISSUE THREAD

**Issue by OlehObodin** [reactioncommerce/mailchimp-open-commerce-helm-chart#39]
How to implement redirection to https using this chart?

I wrote this instructions:
```
annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/cetificate-arn: arn:aws:acm:eu-west-3:999722084027:certificate/6c66eca8-4da5-476f-9529-e6890de3f11a
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
      alb.ingress.kubernetes.io/actions.ssl-redirect: '443'
```
But it is does not help(
